name: ezybook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  firebase_auth: ^5.2.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: 2.4.0
  intl: ^0.19.0
  skeleton_text: ^3.0.1

flutter_native_splash:
  color: "#24BAEC"
  image: assets/images/logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
