name: ezybook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  firebase_auth: ^5.2.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  skeleton_text: ^3.0.1
  firebase_database: ^11.1.0
  firebase_storage: ^12.2.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
