name: ezybook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  firebase_auth: ^5.2.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  skeleton_text: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
